"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i=fpm&fii=g#v@qb4zkz^90uq6w#$5b-9+(^^pkyquz&)bqvze'  # Replace with secure key in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Set to False for production to prevent information leaks

# Allowed hosts for production
ALLOWED_HOSTS = ['yourdomain.com', 'localhost', '127.0.0.1']  # Update with your domain

# Custom user model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'csp',  # Added for Content Security Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Added for CSP
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings to protect against common vulnerabilities
SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS
CSRF_COOKIE_SECURE = True  # CSRF cookies only sent over HTTPS
SESSION_COOKIE_SECURE = True  # Session cookies only sent over HTTPS
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking by disallowing framing
SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to subdomains
SECURE_HSTS_PRELOAD = True  # Allow HSTS preload listing

# Content Security Policy (CSP) settings
CSP_DEFAULT_SRC = ("'self'",)  # Restrict content to same origin
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")  # Allow inline scripts (adjust for external scripts)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # Allow inline styles (adjust for external styles)
CSP_IMG_SRC = ("'self'", "data:")  # Allow images from same origin and data URIs

"""
Security Notes:
- DEBUG=False prevents sensitive information leaks in production.
- SECURE_SSL_REDIRECT ensures all traffic uses HTTPS.
- CSRF_COOKIE_SECURE and SESSION_COOKIE_SECURE protect cookies over HTTPS.
- SECURE_BROWSER_XSS_FILTER and SECURE_CONTENT_TYPE_NOSNIFF add browser-level protections.
- X_FRAME_OPTIONS='DENY' prevents clickjacking.
- HSTS settings enforce HTTPS for one year and support preload.
- CSP settings restrict content sources to mitigate XSS risks.
- Replace SECRET_KEY with a secure value in production (e.g., using environment variables).
- Update ALLOWED_HOSTS with your production domain.
- Install 'django-csp' with 'pip install django-csp' for CSP middleware.
"""